---
- name: Install Prometheus
  package:
    name: prometheus
    state: present

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Reload Prometheus

- name: Ensure Prometheus is running
  systemd:
    name: prometheus
    enabled: yes
    state: started
