---
- name: Install FluentBit
  package:
    name: td-agent-bit
    state: present

- name: Configure FluentBit to send logs to ElasticSearch
  template:
    src: fluentbit.conf.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
  notify:
    - Restart FluentBit

- name: Ensure FluentBit is running
  systemd:
    name: td-agent-bit
    enabled: yes
    state: started
